version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: 'mysql'
       MYSQL_USER: 'root'
       MYSQL_PASSWORD: 'root'
       MYSQL_ROOT_PASSWORD: 'root'
  web:
    build: .
    entrypoint: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/covid_analysis
    ports:
      - "8000:8000"
    depends_on:
      - db
